version: '3.8'

services:
  db_server:
    build: ./database
    container_name: bd_cruzazul
    environment:
      POSTGRES_DB: farmacia_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Inacap.654321
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - azul-net

  frontend_web:
    build: ./frontend
    container_name: web_cruzazul
    ports:
      - "80:80"
    environment:
      - DB_HOST=db_server
      - DB_PASSWORD=Inacap.654321
    depends_on:
      - db_server
    networks:
      - azul-net

networks:
  azul-net:
    driver: bridge

volumes:
  postgres_data: